import type { Metadata, Viewport } from 'next'
import { DM_Sans } from 'next/font/google'
import Script from 'next/script'
import './globals.css'
import LayoutShell from '@/components/LayoutShell'
import StyledJsxRegistry from '@/components/StyledJsxRegistry'

// DM Sans is the ENTIRE typographic system, display headings, body, UI, and
// every numeral. There is deliberately no second family: hierarchy is carried
// by weight (300→800), size, and tracking rather than by a serif/sans pairing.
// `--font-syne` is kept as an alias so any stray reference still resolves to
// DM Sans instead of silently falling back to a system font.
// The real italic is loaded (not just upright): ~57 places set
// `font-style: italic`, the hero's "Jamaica", the about-page pull quotes,
// the confirmation lines. Without an italic face the browser synthesises a
// mechanical slant, which reads as sloppy at display size. Declaring the
// style costs nothing until used: browsers fetch a @font-face only when
// text actually renders in it.
const dmSans = DM_Sans({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
  variable: '--font-dm-sans',
  display: 'swap',
})

const siteUrl = 'https://mapltours.com'

export const metadata: Metadata = {
  metadataBase: new URL(siteUrl),
  title: {
    default: 'MAPL Tours Jamaica | Tours, Transfers & Day Trips',
    template: '%s | MAPL Tours Jamaica',
  },
  description: 'Book Jamaica tours and private airport transfers online: Dunn\'s River, Blue Hole, bamboo rafting, Nine Mile, Rick\'s Cafe. Local drivers, flat prices, no surprises.',
  keywords: [
    'best tours in Jamaica',
    'Jamaica tours',
    'Jamaica cultural experiences',
    'things to do in Jamaica',
    'Jamaica excursions',
    'Negril tours',
    'Falmouth tours',
    'Ocho Rios tours',
    'Montego Bay tours',
    'Jamaica adventure tours',
    'Jamaica food tours',
    'jerk chicken Jamaica',
    'Blue Mountain coffee tour',
    'Dunns River Falls tour',
    'Bob Marley tour Jamaica',
    'bamboo rafting Jamaica',
    'Jamaica snorkeling',
    'Jamaica cliff diving',
    'Ricks Cafe Negril',
    'Jamaica local experiences',
    'authentic Jamaica',
    'Jamaica vacation activities',
    'Jamaica trip planning',
    'Caribbean tours',
    'Jamaica travel',
    // Terms MAPL already ranks for in Google Search Console (high impressions).
    'Nine Mile Jamaica',
    'Nine Mile Bob Marley',
    'Bob Marley Nine Mile tour',
    'Rastafari Indigenous Village',
    'Rastafari village Jamaica',
    'Port Royal Jamaica',
    "Gloria's Port Royal",
    'Ocean Eden Bay',
    'scuba diving Jamaica',
    'diving Jamaica',
    'PADI diving Jamaica',
    'night diving Jamaica',
  ],
  authors: [{ name: 'MAPL Tours Jamaica', url: siteUrl }],
  creator: 'MAPL Tours Jamaica',
  publisher: 'MAPL Tours Jamaica',
  openGraph: {
    type: 'website',
    locale: 'en_US',
    siteName: 'MAPL Tours Jamaica',
    title: 'MAPL Tours Jamaica | Best Tours & Cultural Experiences in Jamaica',
    description: 'Discover the best tours in Jamaica. Authentic cultural experiences crafted by locals. Cliff diving, coffee treks, reggae sessions, jerk cooking, and more.',
    // Image is generated by app/opengraph-image.tsx and picked up
    // automatically by Next.js, no static asset needed.
  },
  twitter: {
    card: 'summary_large_image',
    title: 'MAPL Tours Jamaica | Best Tours & Cultural Experiences',
    description: 'Authentic cultural experiences crafted by locals who know Jamaica best.',
    // Falls back to the same dynamic opengraph-image.
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
  category: 'travel',
}

export const viewport: Viewport = {
  themeColor: '#FFFFFF',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  // Full-bleed reel surfaces extend under the iPhone home indicator; the
  // safe-area env() insets they rely on are 0 unless the viewport is cover.
  viewportFit: 'cover',
}

// JSON-LD structured data for SEO
function JsonLd() {
  const structuredData = {
    '@context': 'https://schema.org',
    '@type': 'TravelAgency',
    name: 'MAPL Tours Jamaica',
    url: siteUrl,
    // Google wants a crawlable raster logo (>=112px); the SVG favicon route
    // is not reliable for this.
    logo: `${siteUrl}/brand/mapl-icon-1024.png`,
    description: 'Discover the best tours in Jamaica. Authentic cultural experiences crafted by locals who know Jamaica best.',
    address: {
      '@type': 'PostalAddress',
      addressCountry: 'JM',
      addressRegion: 'Jamaica',
    },
    geo: {
      '@type': 'GeoCoordinates',
      // Montego Bay / Sangster (MBJ), where every transfer begins. Was the
      // Jamaica country centroid, which contradicted the geo meta tags below.
      latitude: 18.5037,
      longitude: -77.9134,
    },
    // Every locality the business actually serves. The transfers schema listed
    // three (Rose Hall, Lucea, Runaway Bay) that this one omitted, so the two
    // entities disagreed about the service area.
    areaServed: [
      { '@type': 'Country', name: 'Jamaica' },
      { '@type': 'City', name: 'Montego Bay' },
      { '@type': 'City', name: 'Rose Hall' },
      { '@type': 'City', name: 'Falmouth' },
      { '@type': 'City', name: 'Runaway Bay' },
      { '@type': 'City', name: 'Ocho Rios' },
      { '@type': 'City', name: 'Lucea' },
      { '@type': 'City', name: 'Negril' },
      { '@type': 'City', name: 'Nine Mile' },
    ],
    priceRange: '$19 - $459',
    // Note: aggregateRating intentionally omitted from the site-wide entity.
    // Google rejects "self-serving" reviews, ratings/reviews belong on the
    // specific thing reviewed (Product / Service / TouristTrip), not on the
    // business itself. Per-experience ratings live on /experience/[slug].
    hasOfferCatalog: {
      '@type': 'OfferCatalog',
      name: 'Jamaica Tours & Experiences',
      itemListElement: [
        {
          '@type': 'Offer',
          itemOffered: {
            '@type': 'TouristTrip',
            name: "Rick's Cafe Cliff Diving & Sunset",
            description: 'Jump from legendary cliffs as the sun melts into the Caribbean.',
            touristType: 'Adventure',
            offers: { '@type': 'Offer', price: '255', priceCurrency: 'USD' },
          },
        },
        {
          '@type': 'Offer',
          itemOffered: {
            '@type': 'TouristTrip',
            name: 'Bob Marley Nine Mile Pilgrimage',
            description: 'Walk where Bob walked. Feel the spirit of One Love.',
            touristType: 'Culture',
            offers: { '@type': 'Offer', price: '459', priceCurrency: 'USD' },
          },
        },
        {
          '@type': 'Offer',
          itemOffered: {
            '@type': 'TouristTrip',
            name: "Dunn's River Falls Climb",
            description: 'Climb 600 feet of cascading falls hand-in-hand.',
            touristType: 'Adventure',
            offers: { '@type': 'Offer', price: '351', priceCurrency: 'USD' },
          },
        },
      ],
    },
    sameAs: [
      'https://www.instagram.com/mapltoursjamaica',
      'https://www.tiktok.com/@mapltoursjamaica',
    ],
  }

  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }}
    />
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <JsonLd />
        <meta name="google-site-verification" content="NfZAf4Mh4YPVRIeaJT6pHB57jI10V5fTXOgX2WT4k3U" />
        {/* Geo targeting: MAPL Tours operates in Jamaica, anchored on Montego Bay /
            Sangster (MBJ), where every airport transfer begins. */}
        <meta name="geo.region" content="JM" />
        <meta name="geo.placename" content="Montego Bay, Jamaica" />
        <meta name="geo.position" content="18.5037;-77.9134" />
        <meta name="ICBM" content="18.5037, -77.9134" />
        {/*
          Hero image preload was previously a manual `<link rel="preload">`
          pointing at the raw 1920x1080 Pexels URL. That bypassed Next/Image
          entirely and double-loaded the hero (one fat unoptimized copy +
          one Next-optimized copy). The hero <Image> in FeedView already
          carries `priority` + `fetchPriority="high"`, which auto-emits a
          preload tag for the OPTIMIZED variant, so we let Next handle it.
        */}
        <link rel="prefetch" href="/explore" />
        <link rel="dns-prefetch" href="https://lh3.googleusercontent.com" />
        <link rel="dns-prefetch" href="https://eybeezhvuokziyczkkkl.supabase.co" />
        <link rel="dns-prefetch" href="https://www.googletagmanager.com" />
        <link rel="dns-prefetch" href="https://static.hotjar.com" />
        <link rel="dns-prefetch" href="https://script.hotjar.com" />
      </head>
      <body className={dmSans.variable}>
        <StyledJsxRegistry>
          <LayoutShell>{children}</LayoutShell>
        </StyledJsxRegistry>
        <Script src="https://www.googletagmanager.com/gtag/js?id=G-2JVWPL4GBE" strategy="lazyOnload" />
        <Script id="gtag-init" strategy="lazyOnload">
          {`window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-2JVWPL4GBE');
gtag('config', 'AW-18126709990');`}
        </Script>
        <Script id="hotjar" strategy="lazyOnload">
          {`(function(h,o,t,j,a,r){
h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
h._hjSettings={hjid:6688839,hjsv:6};
a=o.getElementsByTagName('head')[0];
r=o.createElement('script');r.async=1;
r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
a.appendChild(r);
})(window,document,'https://static.hotjar.com/c/hotjar-','.js?sv=');`}
        </Script>
      </body>
    </html>
  )
}
