import { HERO, DESTINATIONS, EXPERIENCE_IMAGES } from './images'

export type ExperienceCategory = 'Adventure' | 'Nature' | 'Music' | 'Food' | 'Culture' | 'Water'

export interface Comment {
  id: number
  user: string
  avatar: string
  text: string
  time: string
  likes: number
}

export interface Experience {
  id: number
  destination: string
  parish: string
  title: string
  price: number
  duration: string
  rating: number
  reviews: number
  category: ExperienceCategory
  creator: string
  followers: string
  gradient: string
  emoji: string
  image: string
  video: string
  description: string
  tags: string[]
  highlights?: string[]
  comments: Comment[]
}

export function slugify(title: string): string {
  return title
    .toLowerCase()
    .replace(/['']/g, '')
    .replace(/&/g, 'and')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
}

export function getExperienceBySlug(slug: string): Experience | undefined {
  return experiences.find((e) => slugify(e.title) === slug)
}

export function getSlug(exp: Experience): string {
  return slugify(exp.title)
}

export const CATEGORY_COLORS: Record<ExperienceCategory, string> = {
  Adventure: '#1A1A1A',
  Nature:    '#0A6E3A',
  Music:     '#C8960F',
  Food:      '#B07D0A',
  Culture:   '#2D7A3E',
  Water:     '#1A1A1A',
}

export const HERO_IMAGE = HERO

export const DESTINATION_IMAGES: Record<string, string> = {
  ...DESTINATIONS,
}

// Free stock videos from Pexels (no API key needed for direct links)
const VIDEOS = {
  cliffDiving: 'https://videos.pexels.com/video-files/854572/854572-hd_1920_1080_25fps.mp4',
  mountains: 'https://videos.pexels.com/video-files/3365440/3365440-hd_1920_1080_30fps.mp4',
  music: 'https://videos.pexels.com/video-files/4985239/4985239-hd_1080_1920_25fps.mp4',
  cooking: 'https://videos.pexels.com/video-files/3207798/3207798-hd_1920_1080_24fps.mp4',
  waterfall: 'https://videos.pexels.com/video-files/5744454/5744454-hd_1920_1080_24fps.mp4',
  culture: 'https://videos.pexels.com/video-files/6201022/6201022-hd_1920_1080_25fps.mp4',
  fishing: 'https://videos.pexels.com/video-files/8822474/8822474-hd_1920_1080_30fps.mp4',
  rafting: '/rafting-video.mp4',
  snorkeling: 'https://videos.pexels.com/video-files/3765078/3765078-hd_1920_1080_30fps.mp4',
  streetFood: 'https://videos.pexels.com/video-files/6841012/6841012-hd_1920_1080_30fps.mp4',
  blueHole: 'https://videos.pexels.com/video-files/4055909/4055909-hd_1920_1080_25fps.mp4',
  bioluminescent: 'https://videos.pexels.com/video-files/2558530/2558530-hd_1920_1080_25fps.mp4',
  bobsled: 'https://videos.pexels.com/video-files/5744454/5744454-hd_1920_1080_24fps.mp4',
  rastafari: 'https://videos.pexels.com/video-files/9653702/9653702-hd_1920_1080_25fps.mp4',
  reachFalls: 'https://videos.pexels.com/video-files/6981400/6981400-hd_1920_1080_25fps.mp4',
}

export const experiences: Experience[] = [
  {
    id: 1,
    destination: 'Negril',
    parish: 'Westmoreland',
    title: "Rick's Cafe Cliff Diving & Sunset",
    price: 85,
    duration: '4 hrs',
    rating: 4.9,
    reviews: 1247,
    category: 'Adventure',
    creator: 'yardie.adventures',
    followers: '287K',
    gradient: 'linear-gradient(170deg, #003B5C 0%, #006994 52%, #00B4D8 100%)',
    emoji: '🌊',
    image: EXPERIENCE_IMAGES[1],
    video: VIDEOS.cliffDiving,
    description: 'Jump from legendary cliffs as the sun melts into the Caribbean. The crowd cheers, the rum flows, and the sky turns gold.',
    tags: ['Cliff Diving', 'Sunset', 'Live Music'],
    highlights: ['35-foot cliff jumps', 'Live reggae band at sunset', 'Rum punch included', 'Professional photos available'],
    comments: [
      { id: 1, user: 'TravelJunkie92', avatar: '🧑🏾', text: 'Jumped from the 35ft platform! Scariest and best thing I ever did 🤯', time: '2 weeks ago', likes: 47 },
      { id: 2, user: 'SunsetChaser', avatar: '👩🏽', text: 'The sunset here is unreal. We stayed until the last light faded. Pure magic.', time: '1 month ago', likes: 32 },
      { id: 3, user: 'AdventureAlex', avatar: '🧔🏻', text: 'Marcus our guide was incredible. Made sure everyone felt safe. 10/10', time: '3 weeks ago', likes: 21 },
    ],
  },
  {
    id: 2,
    destination: 'Blue Mountains',
    parish: 'St. Andrew',
    title: 'Sunrise Coffee Trek & Farm Tasting',
    price: 120,
    duration: '6 hrs',
    rating: 4.8,
    reviews: 634,
    category: 'Nature',
    creator: 'peak.jamaica',
    followers: '94K',
    gradient: 'linear-gradient(170deg, #0D2B1B 0%, #1B5E3B 52%, #7B9E3B 100%)',
    emoji: '☕',
    image: EXPERIENCE_IMAGES[2],
    video: VIDEOS.mountains,
    description: 'Hike through misty peaks to Jamaica\'s finest coffee farms. Taste beans straight from the bush at 5,000 feet.',
    tags: ['Hiking', 'Coffee', 'Sunrise'],
    highlights: ['Blue Mountain Peak trail', 'Farm-to-cup tasting', 'Breakfast included', 'Stunning panoramic views'],
    comments: [
      { id: 1, user: 'CoffeeLover_JA', avatar: '👩🏿', text: 'Best coffee I have ever tasted in my life. You can taste the mountain air.', time: '1 week ago', likes: 38 },
      { id: 2, user: 'HikerMike', avatar: '🧑🏼', text: 'Wake up at 3am is brutal but watching sunrise from the peak... worth every minute', time: '2 months ago', likes: 25 },
    ],
  },
  {
    id: 3,
    destination: 'Kingston',
    parish: 'Kingston',
    title: 'Reggae Roots: Studio Session & Sound System',
    price: 95,
    duration: '3 hrs',
    rating: 4.9,
    reviews: 2103,
    category: 'Music',
    creator: 'irie.kingston',
    followers: '421K',
    gradient: 'linear-gradient(170deg, #1A0A00 0%, #4B2A00 52%, #FFB300 100%)',
    emoji: '🎵',
    image: EXPERIENCE_IMAGES[3],
    video: VIDEOS.music,
    description: 'Step inside a real Kingston studio where legends recorded. Feel the bass shake your chest at a neighborhood sound system dance.',
    tags: ['Reggae', 'Studio Tour', 'Sound System'],
    highlights: ['Historic Tuff Gong Studios', 'Meet local musicians', 'Sound system experience', 'Vinyl record souvenir'],
    comments: [
      { id: 1, user: 'ReggaeRoots', avatar: '🧑🏾', text: 'Standing in the same studio where Bob recorded... goosebumps the whole time 🎶', time: '3 days ago', likes: 64 },
      { id: 2, user: 'BassQueen', avatar: '👩🏾', text: 'The sound system session at night is EVERYTHING. You feel the music in your bones.', time: '2 weeks ago', likes: 41 },
      { id: 3, user: 'VinylHead', avatar: '🧔🏾', text: 'Got a signed vinyl from a local artist. This experience is priceless.', time: '1 month ago', likes: 28 },
    ],
  },
  {
    id: 4,
    destination: 'Boston Bay',
    parish: 'Portland',
    title: 'Jerk Pit Master Class with Devon',
    price: 75,
    duration: '4 hrs',
    rating: 4.7,
    reviews: 891,
    category: 'Food',
    creator: 'jerk.legend',
    followers: '156K',
    gradient: 'linear-gradient(170deg, #3D0A00 0%, #8B1A00 52%, #D4521A 100%)',
    emoji: '🔥',
    image: EXPERIENCE_IMAGES[4],
    video: VIDEOS.cooking,
    description: 'Learn the art of jerk from a third-generation pit master. Season, smoke, and feast on the beach where jerk was born.',
    tags: ['Jerk Chicken', 'Cooking Class', 'Beach'],
    highlights: ['Hands-on jerk preparation', 'Secret spice blend recipe', 'Beachside feast', 'Take home spice kit'],
    comments: [
      { id: 1, user: 'FoodieFromTO', avatar: '👨🏽', text: 'Devon is the GOAT. His scotch bonnet sauce recipe changed my life 🔥', time: '5 days ago', likes: 52 },
      { id: 2, user: 'ChefKayla', avatar: '👩🏿', text: 'Real pimento wood smoking, not the fake stuff. This is the birthplace of jerk and you taste the difference.', time: '3 weeks ago', likes: 33 },
    ],
  },
  {
    id: 5,
    destination: 'Ocho Rios',
    parish: 'St. Ann',
    title: "Dunn's River Falls & Hidden Blue Hole",
    price: 110,
    duration: '5 hrs',
    rating: 4.8,
    reviews: 1876,
    category: 'Adventure',
    creator: 'ochorios.vibes',
    followers: '203K',
    gradient: 'linear-gradient(170deg, #003D2E 0%, #006B52 52%, #00A878 100%)',
    emoji: '💧',
    image: EXPERIENCE_IMAGES[5],
    video: VIDEOS.waterfall,
    description: 'Climb 600 feet of cascading falls hand-in-hand, then discover a secret blue hole where locals swim under waterfalls.',
    tags: ['Waterfalls', 'Swimming', 'Nature'],
    highlights: ['Guided waterfall climb', 'Secret Blue Hole access', 'Lunch at jerk center', 'Hotel pickup included'],
    comments: [
      { id: 1, user: 'WaterfallChaser', avatar: '🧑🏻', text: 'The Blue Hole is the real gem here. Barely any tourists, just locals vibing. Incredible.', time: '1 week ago', likes: 45 },
      { id: 2, user: 'FamilyTravel5', avatar: '👩🏼', text: 'Did this with our 3 kids (ages 6-12). They talk about it every single day since we got home 💙', time: '2 months ago', likes: 37 },
    ],
  },
  {
    id: 6,
    destination: 'Nine Mile',
    parish: 'St. Ann',
    title: 'Bob Marley Heritage Pilgrimage',
    price: 145,
    duration: 'Full day',
    rating: 5.0,
    reviews: 3241,
    category: 'Culture',
    creator: 'roots.culture',
    followers: '312K',
    gradient: 'linear-gradient(170deg, #1A2A00 0%, #3A5A00 52%, #7B9B1A 100%)',
    emoji: '🌿',
    image: EXPERIENCE_IMAGES[6],
    video: VIDEOS.culture,
    description: 'Walk where Bob walked. From his childhood home to the rock pillow where he meditated. Feel the spirit of One Love.',
    tags: ['Bob Marley', 'Heritage', 'Rastafari'],
    highlights: ['Bob Marley birthplace tour', 'Mount Zion meditation rock', 'Ital lunch included', 'Live acoustic performance'],
    comments: [
      { id: 1, user: 'OneLove_Forever', avatar: '🧑🏾', text: 'Sitting on the same rock where Bob meditated... I cried. This is a spiritual experience.', time: '4 days ago', likes: 89 },
      { id: 2, user: 'MarleyFan1978', avatar: '👨🏿', text: 'Third time doing this tour. Every time I learn something new. The Rasta guide is incredible.', time: '1 month ago', likes: 56 },
      { id: 3, user: 'CultureVulture', avatar: '👩🏽', text: 'The ital lunch alone is worth the trip. Cooked with love by the local community.', time: '2 weeks ago', likes: 34 },
    ],
  },
  {
    id: 7,
    destination: 'Treasure Beach',
    parish: 'St. Elizabeth',
    title: 'Sunrise Fishing with Local Fishermen',
    price: 65,
    duration: '3 hrs',
    rating: 4.8,
    reviews: 412,
    category: 'Culture',
    creator: 'trench.treasure',
    followers: '67K',
    gradient: 'linear-gradient(170deg, #2B1500 0%, #7B4500 52%, #D4921A 100%)',
    emoji: '🎣',
    image: EXPERIENCE_IMAGES[7],
    video: VIDEOS.fishing,
    description: 'Cast nets at dawn with fishermen who\'ve worked these waters for generations. Cook your catch on the beach.',
    tags: ['Fishing', 'Sunrise', 'Local Life'],
    highlights: ['Traditional fishing methods', 'Cook your own catch', 'Beach breakfast', 'Small group only'],
    comments: [
      { id: 1, user: 'EarlyBirdTravel', avatar: '🧔🏽', text: 'Caught a snapper and they fried it right there on the beach. Best breakfast of my life.', time: '6 days ago', likes: 29 },
      { id: 2, user: 'SlowTravel_Jo', avatar: '👩🏾', text: 'This is the Jamaica tourists don\'t see. Real people, real life, real connection. ❤️', time: '3 weeks ago', likes: 44 },
    ],
  },
  {
    id: 8,
    destination: 'Port Antonio',
    parish: 'Portland',
    title: 'Rio Grande Bamboo Rafting',
    price: 130,
    duration: '3 hrs',
    rating: 4.9,
    reviews: 1534,
    category: 'Nature',
    creator: 'portantonio.raft',
    followers: '88K',
    gradient: 'linear-gradient(170deg, #0A2B0A 0%, #1A5B1A 52%, #2B8B5B 100%)',
    emoji: '🎋',
    image: EXPERIENCE_IMAGES[8],
    video: VIDEOS.rafting,
    description: 'Glide down the Rio Grande on a handmade bamboo raft. Your captain tells stories while the jungle canopy drifts overhead.',
    tags: ['Rafting', 'River', 'Scenic'],
    highlights: ['Handcrafted bamboo raft', 'Expert raft captain', 'Tropical fruit stop', 'Photography opportunities'],
    comments: [
      { id: 1, user: 'JungleVibes', avatar: '🧑🏼', text: 'Our raft captain sang Bob Marley the entire way down. Most peaceful 3 hours ever.', time: '1 week ago', likes: 51 },
      { id: 2, user: 'NatureNerd', avatar: '👩🏻', text: 'Spotted a doctor bird! The bamboo raft is handmade and you can feel the craftsmanship.', time: '2 months ago', likes: 22 },
    ],
  },
  {
    id: 9,
    destination: 'Negril',
    parish: 'Westmoreland',
    title: 'Seven Mile Beach Snorkel & Rum Punch',
    price: 90,
    duration: '3 hrs',
    rating: 4.7,
    reviews: 967,
    category: 'Water',
    creator: 'negril.watersports',
    followers: '145K',
    gradient: 'linear-gradient(170deg, #002B5B 0%, #0066A0 52%, #00B4D8 100%)',
    emoji: '🤿',
    image: EXPERIENCE_IMAGES[9],
    video: VIDEOS.snorkeling,
    description: 'Snorkel crystal reefs just offshore, then float in turquoise shallows with a rum punch in hand. Pure Caribbean vibes.',
    tags: ['Snorkeling', 'Beach', 'Rum Punch'],
    highlights: ['Coral reef snorkeling', 'Equipment provided', 'Unlimited rum punch', 'Beach lounger included'],
    comments: [
      { id: 1, user: 'OceanLover_', avatar: '🧑🏽', text: 'The reef is so close to shore! Saw parrotfish, sea turtles, and a stingray 🐢', time: '5 days ago', likes: 38 },
      { id: 2, user: 'RumPunchQueen', avatar: '👩🏾', text: 'Unlimited rum punch is not a gimmick here. They keep them coming and they are STRONG 🍹', time: '2 weeks ago', likes: 55 },
    ],
  },
  {
    id: 10,
    destination: 'Kingston',
    parish: 'Kingston',
    title: 'Kingston Street Food & Market Crawl',
    price: 55,
    duration: '3 hrs',
    rating: 4.8,
    reviews: 1123,
    category: 'Food',
    creator: 'eat.kingston',
    followers: '198K',
    gradient: 'linear-gradient(170deg, #2B0A1A 0%, #6B1A3A 52%, #C4455A 100%)',
    emoji: '🍖',
    image: EXPERIENCE_IMAGES[10],
    video: VIDEOS.streetFood,
    description: 'Eat your way through Kingston\'s best-kept secrets. Patties, festivals, mannish water -the real flavors of JA.',
    tags: ['Street Food', 'Markets', 'Local Eats'],
    highlights: ['6+ food stops', 'Coronation Market tour', 'Patty taste test', 'Local guide with stories'],
    comments: [
      { id: 1, user: 'EatEverywhere', avatar: '🧔🏿', text: 'The beef patty from Tastee vs Devon House... I am TORN. Both incredible.', time: '3 days ago', likes: 42 },
      { id: 2, user: 'MarketWalker', avatar: '👩🏼', text: 'Coronation Market is overwhelming in the best way. So many colors, smells, flavors. Our guide knew everyone by name.', time: '1 month ago', likes: 31 },
      { id: 3, user: 'VeganTraveler', avatar: '🧑🏾', text: 'They accommodated my vegan diet perfectly. Ital food stall was my favorite stop!', time: '2 weeks ago', likes: 19 },
    ],
  },
  {
    id: 11,
    destination: 'Ocho Rios',
    parish: 'St. Ann',
    title: 'Blue Hole Secret Falls & Rope Swings',
    price: 75,
    duration: '3 hrs',
    rating: 4.9,
    reviews: 2847,
    category: 'Adventure',
    creator: 'jamrock.finest',
    followers: '198K',
    gradient: 'linear-gradient(170deg, #003D4A 0%, #00758A 52%, #00B4CC 100%)',
    emoji: '💎',
    image: EXPERIENCE_IMAGES[11],
    video: VIDEOS.blueHole,
    description: 'Plunge into electric-turquoise limestone pools hidden deep in the jungle. Rope swings, cliff jumps from 6 to 25 feet, and natural waterslides.',
    tags: ['Cliff Jumping', 'Swimming Holes', 'Viral on TikTok'],
    highlights: ['Multiple cliff jump heights (6-25ft)', 'Natural rope swings', 'Hidden limestone pools', 'Jungle trail hike to entrance'],
    comments: [
      { id: 1, user: 'TikTokTravel', avatar: '🧑🏾', text: 'This is the spot from all those TikToks!! Even more beautiful in person. The water is ACTUALLY that blue 💙', time: '2 days ago', likes: 127 },
      { id: 2, user: 'AdrenalineJunkie', avatar: '🧔🏽', text: 'Did the 25-footer. Thought I was gonna die. Best 3 seconds of my life. SEND IT.', time: '1 week ago', likes: 84 },
      { id: 3, user: 'NatureLoverJA', avatar: '👩🏿', text: 'Way better than Dunn\'s River honestly. Less crowds, more raw, the guides are hilarious.', time: '3 weeks ago', likes: 56 },
    ],
  },
  {
    id: 12,
    destination: 'Falmouth',
    parish: 'Trelawny',
    title: 'Luminous Lagoon Bioluminescent Night Swim',
    price: 65,
    duration: '1.5 hrs',
    rating: 4.9,
    reviews: 3891,
    category: 'Nature',
    creator: 'simplylocal.life',
    followers: '13K',
    gradient: 'linear-gradient(170deg, #000B2E 0%, #001A5C 52%, #0040A0 100%)',
    emoji: '✨',
    image: EXPERIENCE_IMAGES[12],
    video: VIDEOS.bioluminescent,
    description: 'Swim in water that glows electric blue with every movement. One of only 4 bioluminescent bays on Earth -and Jamaica\'s is the brightest.',
    tags: ['Bioluminescence', 'Night Tour', 'Bucket List'],
    highlights: ['One of 4 bioluminescent bays worldwide', 'Swim in glowing water', 'Boat ride through Glistening Waters', 'Tours start at sunset'],
    comments: [
      { id: 1, user: 'BucketListBabe', avatar: '👩🏽', text: 'I literally cried. Every time you move your hand the water lights up like a galaxy. This is real life magic.', time: '4 days ago', likes: 203 },
      { id: 2, user: 'PhotoPro_Mike', avatar: '🧑🏻', text: 'Hardest thing I\'ve ever tried to photograph but the memories are burned into my brain forever. GO.', time: '2 weeks ago', likes: 89 },
      { id: 3, user: 'HoneymoonVibes', avatar: '👩🏾', text: 'We did this on our anniversary. Swimming together in glowing water under the stars. I don\'t have words.', time: '1 month ago', likes: 147 },
    ],
  },
  {
    id: 13,
    destination: 'Ocho Rios',
    parish: 'St. Ann',
    title: 'Mystic Mountain Bobsled & Rainforest Zipline',
    price: 110,
    duration: '4 hrs',
    rating: 4.7,
    reviews: 1654,
    category: 'Adventure',
    creator: 'exploringjamaica',
    followers: '59K',
    gradient: 'linear-gradient(170deg, #0A2E0A 0%, #1A6020 52%, #2D9030 100%)',
    emoji: '🛷',
    image: EXPERIENCE_IMAGES[13],
    video: VIDEOS.bobsled,
    description: 'Channel your inner Cool Runnings on a gravity-powered bobsled through 3,280 feet of rainforest hairpin turns. Then zipline over the canopy.',
    tags: ['Bobsled', 'Zipline', 'Cool Runnings'],
    highlights: ['3,280ft bobsled track through jungle', 'Sky Explorer chairlift panoramic views', 'Rainforest zipline canopy tour', '5 min from cruise pier'],
    comments: [
      { id: 1, user: 'CoolRunnings_Fan', avatar: '🧑🏿', text: 'Feel the rhythm, feel the rhyme, GET ON UP it\'s bobsled time!! 🇯🇲 This was INCREDIBLE', time: '1 week ago', likes: 95 },
      { id: 2, user: 'ZiplineQueen', avatar: '👩🏼', text: 'The chairlift up gives you the most insane view of the coastline. Then you zipline back down screaming the whole way 😂', time: '3 weeks ago', likes: 62 },
    ],
  },
  {
    id: 14,
    destination: 'Montego Bay',
    parish: 'St. James',
    title: 'Rastafari Indigenous Village Immersion',
    price: 85,
    duration: '4 hrs',
    rating: 5.0,
    reviews: 978,
    category: 'Culture',
    creator: 'jamaicatravelchannel',
    followers: '45K',
    gradient: 'linear-gradient(170deg, #1A2E00 0%, #3A6000 52%, #5C9010 100%)',
    emoji: '🌍',
    image: EXPERIENCE_IMAGES[14],
    video: VIDEOS.rastafari,
    description: 'Hike through tropical woodland to a living Rastafari village. Learn hand-drumming, eat communal Ital food, and experience genuine Rastafarian philosophy.',
    tags: ['Rastafari', 'Drumming', 'Ital Food'],
    highlights: ['Authentic Rastafari community', 'Hand-drumming workshop', 'Communal Ital meal', 'Organic garden tour'],
    comments: [
      { id: 1, user: 'SpiritualTraveler', avatar: '🧑🏾', text: 'This changed my perspective on life. Not a tourist trap -a real community sharing their way of life. Humbling.', time: '5 days ago', likes: 134 },
      { id: 2, user: 'DrummerBoy_UK', avatar: '🧔🏻', text: 'Learned to play Nyabinghi drums. The elder who taught me has been drumming for 50 years. Pure soul.', time: '2 weeks ago', likes: 76 },
      { id: 3, user: 'VeganWorld', avatar: '👩🏽', text: 'The Ital food was the best meal of my entire Jamaica trip. Everything from the garden, cooked with intention. Beautiful.', time: '1 month ago', likes: 88 },
    ],
  },
  {
    id: 15,
    destination: 'Manchioneal',
    parish: 'Portland',
    title: 'Reach Falls & Rabbit Hole Cave Swim',
    price: 70,
    duration: '3 hrs',
    rating: 4.9,
    reviews: 1203,
    category: 'Nature',
    creator: 'adventuresfromelle',
    followers: '28K',
    gradient: 'linear-gradient(170deg, #0A3018 0%, #1A6030 52%, #2D8A48 100%)',
    emoji: '🕳️',
    image: EXPERIENCE_IMAGES[15],
    video: VIDEOS.reachFalls,
    description: 'Discover Jamaica\'s prettiest waterfall -a 65-foot cascade into emerald pools. Then drop into the Rabbit Hole, an underwater cave you swim through behind the falls.',
    tags: ['Waterfall', 'Cave Swimming', 'Hidden Gem'],
    highlights: ['65-foot wide cascade waterfall', 'Rabbit Hole underwater cave', 'Natural heart-shaped pool', 'Certified guide included'],
    comments: [
      { id: 1, user: 'PortlandPrincess', avatar: '👩🏿', text: 'Born and raised in Portland and this STILL takes my breath away every time. The Rabbit Hole is insane.', time: '3 days ago', likes: 71 },
      { id: 2, user: 'CaveExplorer', avatar: '🧑🏼', text: 'Swimming through the underwater cave and coming out behind a waterfall... I felt like Indiana Jones 😂', time: '2 weeks ago', likes: 93 },
      { id: 3, user: 'NatGeoWannabe', avatar: '🧔🏾', text: 'This is the waterfall that National Geographic called the prettiest in Jamaica. They were right. Skip Dunn\'s River, come here.', time: '1 month ago', likes: 58 },
    ],
  },
  {
    id: 16,
    destination: 'Kingston',
    parish: 'Kingston',
    title: 'Devon House Patty & Ice Cream Tour',
    price: 35,
    duration: '2 hrs',
    rating: 4.8,
    reviews: 2134,
    category: 'Food',
    creator: 'eat.kingston',
    followers: '198K',
    gradient: 'linear-gradient(170deg, #4A2800 0%, #8B5000 52%, #C48A20 100%)',
    emoji: '🥟',
    image: EXPERIENCE_IMAGES[16],
    video: VIDEOS.streetFood,
    description: 'Taste Jamaica\'s most famous patty at Devon House -flaky, golden, stuffed with spiced beef. Then cool down with their legendary ice cream.',
    tags: ['Patties', 'Ice Cream', 'Devon House'],
    highlights: ['Famous Devon House beef patty', 'I Scream ice cream parlour', 'Historic Great House tour', 'Mango and soursop flavors'],
    comments: [
      { id: 1, user: 'PattyKing', avatar: '🧑🏿', text: 'Devon House patty is the GOAT. Flaky crust, perfectly spiced filling. I bought 6 to take home.', time: '4 days ago', likes: 67 },
      { id: 2, user: 'IceCreamAddict', avatar: '👩🏽', text: 'The rum and raisin ice cream here is unreal. Sitting in the garden of this colonial mansion eating ice cream... peak Jamaica.', time: '1 week ago', likes: 45 },
    ],
  },
  {
    id: 17,
    destination: 'Port Royal',
    parish: 'Kingston',
    title: 'Gloria\'s Seafood & Port Royal History Walk',
    price: 60,
    duration: '3 hrs',
    rating: 4.9,
    reviews: 876,
    category: 'Food',
    creator: 'eat.kingston',
    followers: '198K',
    gradient: 'linear-gradient(170deg, #1A3040 0%, #2A5070 52%, #3A80B0 100%)',
    emoji: '🐟',
    image: EXPERIENCE_IMAGES[17],
    video: VIDEOS.cooking,
    description: 'Feast on escovitch fish and festival at Gloria\'s -the legendary seaside restaurant in Port Royal, once the "wickedest city on earth."',
    tags: ['Escovitch Fish', 'Port Royal', 'History'],
    highlights: ['Gloria\'s legendary fried fish', 'Port Royal pirate history walk', 'Fort Charles tour', 'Sunset over Kingston Harbour'],
    comments: [
      { id: 1, user: 'HistoryBuff_JA', avatar: '🧔🏾', text: 'Port Royal used to be bigger than New York. Walking these streets knowing pirates ruled here... then eating the best fish of your life at Gloria\'s. Incredible.', time: '5 days ago', likes: 54 },
      { id: 2, user: 'SeafoodLover', avatar: '👩🏿', text: 'The escovitch fish at Gloria\'s is the benchmark. Every other fish I eat in Jamaica, I compare it to this.', time: '2 weeks ago', likes: 41 },
    ],
  },
  {
    id: 18,
    destination: 'Montego Bay',
    parish: 'St. James',
    title: 'Scotchies Jerk Centre & Rum Bar Crawl',
    price: 50,
    duration: '3 hrs',
    rating: 4.7,
    reviews: 1543,
    category: 'Food',
    creator: 'jamaicatravelchannel',
    followers: '45K',
    gradient: 'linear-gradient(170deg, #3A1500 0%, #7A3000 52%, #B45A10 100%)',
    emoji: '🍗',
    image: EXPERIENCE_IMAGES[18],
    video: VIDEOS.cooking,
    description: 'Start at Scotchies -the most famous jerk centre in Jamaica. Then crawl through MoBay\'s best rum bars tasting overproof and craft cocktails.',
    tags: ['Scotchies', 'Rum Tasting', 'Jerk'],
    highlights: ['Scotchies original jerk centre', '3 rum bar stops', 'Wray & Nephew overproof tasting', 'Local craft cocktails'],
    comments: [
      { id: 1, user: 'RumRunner', avatar: '🧑🏾', text: 'Scotchies jerk is cooked on pimento wood right in front of you. The smoke, the spice, the pepper sauce... nothing compares.', time: '3 days ago', likes: 72 },
      { id: 2, user: 'MoBayLocal', avatar: '👩🏿', text: 'Finally someone doing a proper rum crawl! The third bar had a rum punch that nearly knocked me out 🤣', time: '1 week ago', likes: 38 },
    ],
  },
  {
    id: 19,
    destination: 'Ocho Rios',
    parish: 'St. Ann',
    title: 'Miss T\'s Kitchen Cooking Experience',
    price: 80,
    duration: '4 hrs',
    rating: 4.9,
    reviews: 967,
    category: 'Food',
    creator: 'ochorios.vibes',
    followers: '203K',
    gradient: 'linear-gradient(170deg, #2A1A00 0%, #5A3A00 52%, #8A6A10 100%)',
    emoji: '🍛',
    image: EXPERIENCE_IMAGES[19],
    video: VIDEOS.cooking,
    description: 'Cook authentic Jamaican dishes with Miss T -curry goat, oxtail, ackee & saltfish. Her kitchen has been featured on CNN and Anthony Bourdain.',
    tags: ['Cooking Class', 'Curry Goat', 'Ackee & Saltfish'],
    highlights: ['Cook 3 traditional dishes', 'Miss T\'s secret recipes', 'Featured on CNN Travel', 'Take home recipe booklet'],
    comments: [
      { id: 1, user: 'CookingClass_Fan', avatar: '🧑🏼', text: 'Miss T taught me to make curry goat that my Jamaican friends said was "legit." Highest compliment ever.', time: '6 days ago', likes: 63 },
      { id: 2, user: 'FoodieNomad', avatar: '👩🏾', text: 'Anthony Bourdain ate here for a reason. Miss T is a national treasure. The oxtail recipe alone was worth the trip.', time: '3 weeks ago', likes: 81 },
    ],
  },
]
